### ISSUE TITLE
No 3.10 branch on speed.python.org

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/pyperformance#100]
https://speed.python.org/comparison/ has no 3.10 branch.

I tried to investigate a way to fix this but I'm not too sure where the branch configurations are stored. Does anyone know if they're at https://github.com/zware/codespeed or somewhere else?

**Comment by pablogsal** [comment]
> https://speed.python.org/comparison/ has no 3.10 branch.

That happens because 3.10 is not released. The branches you see are, for now, one-off runs that we create when the final version is formally released

**Comment by Fidget-Spinner** [comment]
> > https://speed.python.org/comparison/ has no 3.10 branch.
> 
> That happens because 3.10 is not released. The branches you see are, for now, one-off runs that we create when the final version is formally released

D'oh I didn't know that. Thanks!
