### ISSUE TITLE
Add a tag for the 1.0.2 release.

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/pyperformance#117]
When 1.0.2 was released, a tag did not created.  It would be tagged at 6484a40909312f373c8cfa8c05faec592288abb3, right.

**Comment by pablogsal** [comment]
There is a tag for 1.0.2 here: https://github.com/python/pyperformance/releases/tag/1.0.2

**Comment by ericsnowcurrently** [comment]
Sorry, not sure how I missed that.
