### ISSUE TITLE
`MANIFEST.in` lacks `bm_*/requirements.txt`.

### ISSUE THREAD

**Issue by oraluben** [python/pyperformance#126]
**How to reproduce the issue**

Install a local pyperformance from another directory, e.g. `pip install ../pyperformance`,
then run benchmarks have additional dependencies, e.g. `pyperformance run -b chameleon`.
Run will fail and you can find there's no requirements.txt under installed `bm_chameleon/`.

This occurs to me when I'm using a forked of pyperformance to test my own package.
If folks are developing pyperformance itself, this won't be an issue because the repo root will be current directory and benchmarks in cwd, rather than the installed ones, will be used, so requirements can be found as expected.

PS: I'm using `pip install -e` as a workaround.

**Comment by oraluben** [comment]
I still don't see the full picture of `pip install`, the reproducer seems not to reproduce every time. But `python setup.py bdist` does give the wrong result in `build/`.

**Comment by ericsnowcurrently** [comment]
Good catch.
