### ISSUE TITLE
Running on Windows from cpython repo is broken (and on Mac)

### ISSUE THREAD

**Issue by gvanrossum** [python/pyperformance#144]
I have a repo where I'm developing changes to CPython and I want to run PyPerformance using the python executableI've built here. That executable is named `$REPO\PCbuild\amd64\python.exe` (the `amd64` name is a configuration option IIUC). But the code in `_pythoninfo.py` in `_inspect_python_install` assumes it is `$REPO/python`.

As a workaround I am using
```
        if os.name == "nt":
            base_executable = os.path.join(
                os.path.dirname(stdlib_dir),
                'PCbuild\\amd64\\python.exe',
            )
```

Note that on macOS the assumption is also broken -- there the executable is `$REPO/python.exe`.

**Comment by gvanrossum** [comment]
Note that @zooba tells me that on Windows, stdlib *always* ends in `Lib`, so that test is also wrong. :-)

**Comment by gvanrossum** [comment]
And a better way get the path on Windows is
```
base_executable = sys._base_executable
```

**Comment by gvanrossum** [comment]
The right way to check for a dev build is `sysconfig.is_python_build()` (poorly named but that's what it returns).

**Comment by ericsnowcurrently** [comment]
@gvanrossum, if that didn't fix the problem then please re-open the issue.

**Comment by gvanrossum** [comment]
Seems to work. I left some comments on the PR.

**Comment by ericsnowcurrently** [comment]
This should be fixed now.  (https://github.com/python/pyperformance/pull/154: https://github.com/python/pyperformance/commit/b13bb1ed9075834f9b86a27a3ce2d21377cd11e4)

**Comment by gvanrossum** [comment]
Much better. I notice that for benchmarks that fail to build (e.g. dulwich, sqlalchemy_imperative) the build errors are printed four times -- twice in the default venv, seemingly because pip first tries `setup.py bdist_wheel` and then `setup.py install`, and then pyperformance retries in a "unique venv", where the same thing happens again. (Or it's possible that pip just prints the same error log twice?)

Also, there's still something wrong with installing dulwich and greenlet, it seems installing manually works, but pyperformance gives errors.

(Gotta go, sorry.)
