### ISSUE TITLE
Creating venvs takes very long on Windows

### ISSUE THREAD

**Issue by gvanrossum** [python/pyperformance#146]
On Windows, creating the venvs takes a long time (20-30 minutes). And when re-running, it takes a little less long but still very long (5-10 minutes?).

I wonder if we couldn't share the venv at least for those benchmarks that don't install third party packages (other than pyperformance and its dependencies -- packaging, pyperf, pyparsing, toml).

Most benchmarks don't depend on anything else, so this would be a huge speedup for starting the benchmarks.

**Comment by ericsnowcurrently** [comment]
A small portion of this is fixed with #151.  I should have a PR for the rest up tomorrow.

**Comment by ericsnowcurrently** [comment]
@gvanrossum, sorry for the delay.  I've pushed up some changes that should help speed things up.  If that isn't enough, I have a few other ideas we can try out.
