### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by gvanrossum** [python/pyperformance#177]
It's about time we do another release. @pablogsal has volunteered to do it. But we're waiting for some documentation updates from @ericsnowcurrently.

**Comment by ericsnowcurrently** [comment]
See #177.

Also, we were going to update the docs about the CLI.

**Comment by gvanrossum** [comment]
This *is* #177. Did you mean to link somewhere else?

**Comment by gvanrossum** [comment]
I'm working on the usage docs now, see #178.

**Comment by ericsnowcurrently** [comment]
> This _is_ #177. Did you mean to link somewhere else?

I meant #176.  I've fixed it.

**Comment by pablogsal** [comment]
I have released 1.0.5 and updated the server so I am closing this issue :)

**Comment by gvanrossum** [comment]
Thank you! Goodnight.

**Comment by pablogsal** [comment]
Seems that the data is back on the server. Here is today's main against 3.10:
![Screenshot 2022-04-14 at 00 08 50](https://user-images.githubusercontent.com/11718525/163284260-48d7b995-e686-4543-a94a-66e66e566fcb.png)
