### ISSUE TITLE
Benchmark suggestion: deepcopy

### ISSUE THREAD

**Issue by eendebakpt** [python/pyperformance#199]
One python method that is currently not in the pyperformance benchmarks is `deepcopy` (at least not in the benchmarks that execute on my system).

Can we add a benchmark specifically for `deepcopy`?

In [#91610](https://github.com/python/cpython/pull/91610) (reimplement `deepcopy` in C) there is a simple benchmarking script for `deepcopy`. It is a simple execution of `deepcopy` on a `dict` and a `dataclass`. The benchmark is really simple (not embedded program), but it is representative for the cost of `deepcopy` that I encountered in larger projects. 

If required, I can create a PR with a benchmark similar to the one in [#91610](https://github.com/python/cpython/pull/91610).

**Comment by ericsnowcurrently** [comment]
I'd say give writing the benchmark a try.

**Comment by eendebakpt** [comment]
@ericsnowcurrently #201 is the PR for the benchmark
