### ISSUE TITLE
Add `pyperformance` to `python` PyPI organisation

### ISSUE THREAD

**Issue by hugovk** [python/pyperformance#370]
Following https://discuss.python.org/t/request-python-organisation-on-pypi/26545, we now have two organisations on PyPI: https://pypi.org/org/cpython/ and https://pypi.org/org/python/

We can add the `pyperformance` PyPI project to one of the organisations.

The main benefits are:

* Visibility: we'll be able to see our packages under a PyPI org page

* Maintainability: we can share granular PyPI access to improve the bus factor

Would you like to add this package to one of the orgs?

We should follow the [SC's categorisation](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/5) when deciding which one to use:

> * `cpython`: for development tools that are tied fairly closely to CPython development. This could for example include blurb and cherry-picker. Users generally shouldn’t have to care except for developing CPython itself (although that doesn’t mean the tools necessarily have to be unusable for anyone else).
> * `python`: for general-audience projects that are maintained the Python Core Devs. An example for this category would be tzdata.

Which org do you think is most suitable?

**Comment by diegorusso** [comment]
I think `pyperformance` should belong to `cpython` organisation  as it is our de facto tool to track performance while developing CPython. It is mainly used by people who contribute to CPython.
On the other hand, `pyperf` should belong to `python`: this is a generic performance framework that users can use to track performance of a generic application. This could be use by anyone who wants to track performance of some application. `pyperformance` is based on `pyperf`

**Comment by vstinner** [comment]
I hope that one day, other Python implementations would use pyperformance :-) For now, it seems mainly used by CPython.

**Comment by mdboom** [comment]
My vote is for `python` org (same reasons as @ericsnowcurrently), but I don't feel that strongly either way.

**Comment by Fidget-Spinner** [comment]
> I hope that one day, other Python implementations would use pyperformance :-) For now, it seems mainly used by CPython.

@vstinner PyPy and GraalPy use pyperformance, but I think an older version.

**Comment by hugovk** [comment]
I count four votes for `python` and one for `cpython`, so let's go for `python`.

@corona10 or @pablogsal, please could you add me as an "owner" to https://pypi.org/project/pyperformance/ and I'll add it to the `python` organisation?

**Comment by pablogsal** [comment]
> I count four votes for `python` and one for `cpython`, so let's go for `python`.
> 
> 
> 
> @corona10 or @pablogsal, please could you add me as an "owner" to https://pypi.org/project/pyperformance/ and I'll add it to the `python` organisation?

What username should we use?

**Comment by hugovk** [comment]
I'm `hugovk` there as well.

**Comment by pablogsal** [comment]
Done you should have an invitation

**Comment by hugovk** [comment]
Thanks, added!

* https://pypi.org/project/pyperformance/
* https://pypi.org/org/python/

@corona10 Please could you turn on 2FA for your PyPI account? https://pypi.org/help/#twofa

**Comment by corona10** [comment]
@hugovk Done :)
