### ISSUE TITLE
Use uv instead of pip for setting up venvs for benchmarking

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/pyperformance#373]
I'm thinking of ways to speed up benchmarking.  @colesbury suggested perhaps uv can speed up setting up the benchmarks.

**Comment by corona10** [comment]
Looks good to me, In Karrot we migrated several projects to use uv, I noticed that it shows a lot of speed up.

**Comment by hauntsaninja** [comment]
Note uv doesn't compile bytecode by default, so you may want to pass --compile-bytecode

**Comment by Fidget-Spinner** [comment]
Just an update: on my computer, half the time running the benchmark is spent setting up the venvs. So hopefully this pays off.

**Comment by Fidget-Spinner** [comment]
That doesn't sound worth the additional maintenance burden of supporting two package managers. I'm closing this issue for now. Feel free to reopen if you feel it's worth it!

**Comment by zanieb** [comment]
I'd be interested in revisiting this. As a uv maintainer, it pains me to spend several minutes waiting for the environments to be created — especially when running with `--fast` to test the benchmarking setup.

Is the bar that we need to demonstrate enough speed-up to justify maintaining a shim to uv?

**Comment by Fidget-Spinner** [comment]
@zanieb we moved the issue to here sort of https://github.com/faster-cpython/bench_runner/issues/317. Sorry I don't have a branch to point you to.

**Comment by Fidget-Spinner** [comment]
Also we found that depending on setup, some people spend **hours** waiting for venv setup :cry:

**Comment by mdboom** [comment]
Yeah, IMHO, the requirements are (1) uv should be optional, (2) creating multiple venvs in parallel has the potential to create non-deterministic results, so we can't do that, (3) we need to confirm the resulting venvs are identical (and add a unit test to ensure that going forward).  I'm not too worried about the added complexity (it should be approximately `pip install` -> `uv pip install`).

It also would be nice to get to the bottom of why there is a huge discrepancy in runtimes for some folks.  That's mostly curiosity, though.  I suspect it comes down to environmental differences, like filesystem being used, and "reinstall your OS to use X filesystem" wouldn't be a viable solution for most.
