### ISSUE TITLE
Potential TypeError in bm_chaos.py:68

### ISSUE THREAD

**Issue by rmonat** [python/pyperformance#57]
In bm_chaos.py, in the definition of function [GetKnots](https://github.com/python/pyperformance/blob/master/pyperformance/benchmarks/bm_chaos.py#L68), I think that adding a list with a range object raises a TypeError in Python 3.x:
```python
def GetKnots(points, degree):
    knots = [0] * degree + range(1, len(points) - degree)
    knots += [len(points) - degree] * degree
    return knots
```

This function isn't called in the actual benchmark [due to a test in Spline init](https://github.com/python/pyperformance/blob/master/pyperformance/benchmarks/bm_chaos.py#L79). Could we change the first line of GetKnots with
```python
    knots = [0] * degree + list(range(1, len(points) - degree))
```

**Comment by vstinner** [comment]
Well... since the function is never called, I just removed it in commit 6690642ddeda46fc5ee6e97c3ef4b2f292348ab8 :-)
