### ISSUE TITLE
Tornado issue

### ISSUE THREAD

**Issue by cycyyy** [python/pyperformance#75]
Hi, 
     I'm trying to run the bm_tornado_http.py with "tornado 6.0.3" and I got the following errors:
"
Traceback (most recent call last):
  File "bm_tornado_http.py", line 17, in <module>
    from tornado.gen import coroutine, Task
ImportError: cannot import name 'Task'
"
 I think it's caused by the wrong version of the tornado but I have no idea how to fix it.

Thanks

**Comment by vstinner** [comment]
Did you close the issue because you found a way to run the benchmark properly?
