### ISSUE TITLE
check this 

### ISSUE THREAD

**Issue by SouvikSSG** [python/pyperformance#80]
https://github.com/python/pyperformance/blob/a041ab22e4c1030cbf831f898e805cd7b3a08a66/pyperformance/venv.py#L223

**Comment by lazka** [comment]
@SouvikSSG ??

**Comment by SouvikSSG** [comment]
@lazka a suggestion came on for the correction.

**Comment by lazka** [comment]
Sorry, I don't understand what you are trying to say.

* What problem did you encounter with pyperformance?
* What did you expect to happen instead?

Please try to answer both questions, thanks.

**Comment by vstinner** [comment]
Reopen if you want to report a real issue. That just looks like spam.

**Comment by SouvikSSG** [comment]
@vstinner @lazka It looks the line 'class VirtualEnvironment(object):' isn't doing anything here.

_
 
> https://github.com/python/pyperformance/blob/a041ab22e4c1030cbf831f898e805cd7b3a08a66/pyperformance/venv.py#L223

**Comment by lazka** [comment]
Can you answer my questions from before?

**Comment by SouvikSSG** [comment]
I've no problem encountered with pyperformance, I'm expecting to write a better code with no issues.
